twitterConsumerKey: fx95oKhMHYgytSBmiAqQ
twitterConsumerSecret: 0zfaijLMWMYTwVosdqFTL3k58JhRjZNxd2q0i9cltls

database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:sprout.db
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* Homework Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

logging:
  appenders:
    - type: console
      threshold: DEBUG
      target: stderr
    - type: file
      threshold: INFO
      currentLogFilename: ./logs/sproutsocial/homework.log
      archivedLogFilenamePattern: ./logs/sproutsocial/homework-%d.log.gz
      archivedFileCount: 3
      timeZone: UTC
